### ISSUE TITLE
"Tip us" paywall link in README is broken

### ISSUE THREAD

**Issue by Entryist** [lnbits/lnbits-legend#664] opened 2022-06-11 22:33 UTC
The README [Tip us section](https://github.com/lnbits/lnbits-legend#tip-us) links to a [dead paywall](https://lnbits.com/paywall/GAqKguK5S8f6w5VNjS9DfK) with a 404 error.

**Comment by callebtc** [comment] 2022-06-15 10:58
@arcbtc needs to update the link to `legend.*`

**Comment by callebtc** [comment] 2022-06-15 10:59
Duplicate of #647. Closing.

**Closed by callebtc** 2022-06-15 10:59 UTC
